version: "3"

services:
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: "memes_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: "minio_access"
      MINIO_SECRET_KEY: "minio_secret"
    command: server /data
